/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        ink: '#1B2A33',
        granite: '#4F5E66',
        mist: '#CBD5DA',
        glacier: '#EDF1F3',
        snow: '#FAFBFC',
        river: '#1D5E6B',
        'river-tint': '#DCEBEE',
        milestone: '#F7C600',
        // Risk scale
        'risk-low': '#2E7D57',
        'risk-low-tint': '#E3F1EA',
        'risk-mod': '#D49A00',
        'risk-mod-tint': '#FAF0D2',
        'risk-high': '#C4470F',
        'risk-high-tint': '#F8E3D8',
        'risk-sev': '#9B1C31',
        'risk-sev-tint': '#F3DADF',
        // Night palette
        'night-bg': '#0E181D',
        'night-surface': '#16242B',
        'night-text': '#E6EDF0',
        'night-muted': '#9DB0B8',
        'night-line': '#2B3D46',
        'night-low': '#4DB383',
        'night-mod': '#F0B429',
        'night-high': '#F2793F',
        'night-sev': '#F0647A',
      },
      borderRadius: {
        xs: '2px',
        sm: '6px',
        md: '10px',
        lg: '16px',
        full: '999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        base: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
      },
      fontFamily: {
        sans: ['IBMPlexSans_400Regular'],
        'sans-medium': ['IBMPlexSans_500Medium'],
        'sans-semibold': ['IBMPlexSans_600SemiBold'],
        condensed: ['IBMPlexSansCondensed_500Medium'],
        'condensed-semibold': ['IBMPlexSansCondensed_600SemiBold'],
        'condensed-bold': ['IBMPlexSansCondensed_700Bold'],
        devanagari: ['IBMPlexSansDevanagari_400Regular'],
        'devanagari-medium': ['IBMPlexSansDevanagari_500Medium'],
        'devanagari-semibold': ['IBMPlexSansDevanagari_600SemiBold'],
      },
    },
  },
  plugins: [],
};
